### ISSUE TITLE
comment can't be set using ExternalContext.addResponseCookie

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4156]
As stated in the javaDoc of ExternalContext.addResponseCookie, there are various 'properties' that can be set using the Map parameter.

But the list of supported property keys (see com.sun.faces.context.ExternalContextImpl$ALLOWABLE_COOKIE_PROPERTIES) doesn't allow for the value comment.

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
