### ISSUE TITLE
ui:fragment is counted as new column in h:panelGrid element

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4188]
<h:panelGrid columns="3">
<ui:fragment rendered="true">
<h:panelGroup>
<p:outputLabel
value="test"
for="mail" />
</h:panelGroup>
<h:panelGroup>
<p:inputText id="mail" />
</h:panelGroup>
<p:outputLabel value="test"/>
</ui:fragment>

<h:panelGroup>
<p:outputLabel
value="test"
for="mail" />
</h:panelGroup>
<h:panelGroup>
<p:inputText id="mail" />
</h:panelGroup>
<p:outputLabel value="test"/>

</h:panelGrid>

In this example i would expect 2 rows (panelGrid columns parameter is set to 3) with three td elements each. In this case I get 2 rows, one with 3 td tags, and one with only one td tag. Ui:fragment is supposed to be let's say invisible but in this case it isn't. (In this example i'm trying to not display only one row from the table depending on some condition from bean)

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue

**Comment by BalusC** [comment]
For the record, this is expected behavior. `<ui:fragment>` is an `UIComponent`.

Use `<c:if test="#{bean.show}">` instead.
