### ISSUE TITLE
JSF loss input stream and doesn't build pages correctly

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4201]
Only on Linux never in Windows
O.S RedHat CentOS 6.6
WildFly 10.1
Mojarra 2.2.13

Sometime application lose render capability (pages aren't builted properly on server) and this is an stack a part of stacktrace
java.lang.NullPointerException
at com.sun.faces.application.resource.ResourceHelper$ELEvaluatingInputStream.close(ResourceHelper.java:856)
at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
...

at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:153)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:655)

Watching GrepCode I found the piece of code that throw the exception
@Override
851 public void More ...close() throws IOException {
852
853 if (endOfStreamReached && !expressionEvaluated)

{ 854 info.disableEL(); 855 }

856 inner.close();
857 super.close();
858
859 }

Where inner was teorically setted on
public More ...ELEvaluatingInputStream(FacesContext ctx,
682 ClientResourceInfo info,
683 InputStream inner)

{ 684 685 this.inner = inner; 686 this.info = info; 687 this.ctx = ctx; 688 689 }

Do you have any suggestion? Some timeout, some extra configuration or tips on linux system?
It's possible to catch the Exception and reinitialize in some way the application?

Vincenzo
#### Environment
RedHat CentOS 6.6.x
WildFly 8.2.1 and 10.x
#### Affected Versions
[2.2.8, 2.2.13]

**Comment by kukel** [comment]
Some additional info after some investigation can be found in a PrimeFaces forum post  https://forum.primefaces.org/viewtopic.php?f=3&t=62080&sid=89e41ea2bda919d3fa44c55c4809a459#p182190

I strongly suspect this NPE masks an additional error but I'm not sure. Trying to create a small non-jsf test to substantiate/prove this.

**Comment by kukel** [comment]
It does not seem to be caused by some exeption masking.  Rather that one of the implentations of [ResourceHelper#getNonCompressedInputStream(...)](https://github.com/eclipse-ee4j/mojarra/blob/2.3.14/impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java#L330)

    /**
     * If a {@link ResourceInfo} is not compressable, {@link #getInputStream(ResourceInfo, javax.faces.context.FacesContext)}
     * will call this method to return a stream to the actual resource.
     *
     * @param info  the resource to obtain an InputStream to
     * @param ctx the {@link FacesContext} for the current request
     * @return an InputStream to the resource
     * @throws IOException if an error occurs obtaining the stream
     */
    protected abstract InputStream getNonCompressedInputStream(ResourceInfo info,
                                                               FacesContext ctx)
    throws IOException;

To be found in
- [WebappResourceHelper#getNonCompressedInputStream](https://github.com/eclipse-ee4j/mojarra/blob/2.3.14/impl/src/main/java/com/sun/faces/application/resource/WebappResourceHelper.java#L127)
- [ClasspathResourceHelper#getNonCompressedInputStream](https://github.com/eclipse-ee4j/mojarra/blob/2.3.14/impl/src/main/java/com/sun/faces/application/resource/ClasspathResourceHelper.java#L119)

(there is a [third one](https://github.com/eclipse-ee4j/mojarra/blob/2.3.14/impl/src/main/java/com/sun/faces/application/resource/FaceletWebappResourceHelper.java#L237) but that directly throws a `UnupportedOoperationException`) 

Actually returns null.  Considering all code that was executed before this, the ResourceInfo used in these methods is not null, nor all its content (path etc...) Can there be a reason for the inputStream becoming null? Caching? Redeploy? I suspect some caching since it seems to have worked and stops working. 

Any ideas?

P.S. I'm not the one having the issue, just investigating it.

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
