### ISSUE TITLE
Backport the fix for JAVASERVERFACES-4195 to 2.1.x.

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4220]
Backport [the fix](https://github.com/javaserverfaces/mojarra/commit/7b8b118e418d40d9b708eddfbaf833ed9f57d8c2) for #4199 to <tt>2.1.x</tt>.
#### Affected Versions
[2.1.29-09]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
