### ISSUE TITLE
unable to validate expressions with method invocations

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4228]
javax.faces.validator.ValueExpressionAnalyzer$InterceptingResolver should also override (and delegate) the method "invoke" from ELResolver otherwise the BeanValidator wouldn’t support expressions with method invocations (e.g. #

{exampleBean.anyMethod(anyParam).value}

.

Currently it doesn’t override the method so the default implementation is taken which returns null and leads to problems…

proposed solution: [https://github.com/treblereel/jboss-jsf-api_spec/commit/19738f4eadf2987b160e2a9eceff4ae3fa25cd55](https://github.com/treblereel/jboss-jsf-api_spec/commit/19738f4eadf2987b160e2a9eceff4ae3fa25cd55)
#### Affected Versions
[2.1.29-10]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
