### ISSUE TITLE
BeanValidation does not work with full state saving

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4239]
BeanValidation is not fired during ValidationPhase when full state saving is configured in web.xml.
The problem appears in many versions, from 2.1.28 on and later. It came in with the change in ComponentValidators.addDefaultValidatorsToComponent() (in January 2014?), where adding was restricted to RESTORE_VIEW_PHASE. When full state saving is configured, the component tree is not build newly from scratch, so the addDefaultValidatorToComponent() method is not called at all.
#### Environment
Tomcat 8.0.26, Java 8
#### Affected Versions
[2.2.8-19]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
