### ISSUE TITLE
Set FACELETS_REFRESH_PERIOD to -1 if project stage is Production - FaceletCacheFactoryImpl

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4241]
Related to issue #3791.

If I do not set FACELETS_REFRESH_PERIOD, it is defaulted to '-1' in Production PROJECT_STAGE in com.sun.faces.application.ApplicationAssociate.createFaceletFactory method.

But in com.sun.faces.facelets.impl.FaceletCacheFactoryImplgetFaceletCache method it is not defaulted to '-1' but to '2' as it is defined in enum WebContextInitParameter.FaceletsDefaultRefreshPeriod.

The cache has interval "2000" if FACELETS_REFRESH_PERIOD not set (should be -1000) and interval "-1000" if FACELETS_REFRESH_PERIOD set explicitly to '-1' (both in Production PROJECT_STAGE).

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
