### ISSUE TITLE
FacesContext#setViewRoot() should not clear RENDERED_RESOURCE_DEPENDENCIES during a non-@all partial request

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4249]
Currently, `FacesContext#setViewRoot()` calls `RequestStateManager#clearAttributesOnChangeOfView()` when a view has been changed. However, when `PartialViewContext#isAjaxRequest()` returns `true` and `PartialViewContext#isRenderAll()` returns `false`, then it should not clear context attribute `RENDERED_RESOURCE_DEPENDENCIES` as it will otherwise cause `ResourceHandler#isResourceRendered()` to falsely return `false` when it was `true` on the initial view.

**Comment by xqvier** [comment]
Hello,

Since this modification, it appears that we're not able to do an ajax request which update @all and land on the same view.
In this case, the method ` RequestStateManager#clearAttributesOnChangeOfView() ` isn't called.

The workaround here is to not do ajax request with update @all when staying on the same page but this didn't cause any issue on previous version. 

Is it intended ?
