### ISSUE TITLE
UIRepeat visitTree resets Index correctly

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4261]
When using UIRepeat then FaceletViewHandlingStrategy.reapplyDynamicActions is not working properly. Only the first dynamic action to add/remove a component which is a sibling of UIRepeat will be reapplied. This is due to the visitTree method inside UIRepeat. It looks like index is not reset properly.

When visitTree is called the first time, I have the following situation:
- UIRepeat.index = -1
- getDataModel().getRowIndex() = 0

Called from reapplyDynamicActions (locateComponentByClientId) the visitTree method also visits the rows of UIRepeat. Before doing so it saves the oldRowIndex, which is 0, just to reset the index in the end. But resetting the index to 0 is exactly the problem: after the first run of visitTree all subsequent calls to UIRepeat.getClientId() return the clientId including index 0. This breaks all other dynamic actions for siblings of UIRepeat, which do not have an index in their clientId.

It seems like UIRepeat should save its own index as oldRowIndex and furthermore it should resetClientIds after resetting the index to oldRowIndex if oldRowIndex==-1.

**Comment by gndrm** [comment]
After debugging this for some time the reason for the Bug is now clear.

First, UIRepeat really should reset ClientIds when resetting Index to -1.
Second, when an ajax request is submitted, the RestoreView Phase kicks in and runs visitTree with SKIP_ITERATION hint. This hint is ignored by UIRepeat in case the ajax source is one of UIRepeats children (see requiresRowIteration method). This behavior is necessary for processUpdates. But when restoring the view it breaks view reconstruction when restoring dynamic components inside UIRepeat rows.

**Comment by BalusC** [comment]
I've merged it, but it turns out that it broke `Issue3833IT`, so I had to revert it.

Please review and re-create PR and make sure all tests pass.

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
