### ISSUE TITLE
Usage of (in JRE 9) deprecated API

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4293]
Mojarra (tested 2.3.2) depends on package javax.xml.bind. For example in com.sun.faces.util.ByteArrayGuardAESCTR.java to javax.xml.bind.DatatypeConverter .

This API is deprecated in Java 9 SE and only accessible with jvm command line argument --add-module java.bind.xml .
A more secure/promising option would be to provide the implementation (https://github.com/javaee/jaxb-v2) as module or in the classpath, which will result to  a dependency of at least 3 other jars even for a rather short sample JSF app using a simple servlet runner like Tomcat. I know that full JEE container already might contain these JAXB jars in their classpath.

Thus, I would vote to remove the dependency in Mojarra sooner than later, if hopefully possible. Otherwise, any JSF developer using Tomcat (or similar) may have problems when upgrading to Java 9. A big benefit of Mojarra always was its possibility of independent usage, maybe with the exception of CDI, and not falling into the jar dependency hell. There are developer (like me :) ) who like to see what is going on instead of using the automatic dependency resolution of Maven or similar. This keeps an application small and clean.

Thanks fpr Mojarra,
Chris

**Comment by bshannon** [comment]
It seems fine to turn JAXB into a soft dependency, so that it works if JAXB is
available but doesn't require JAXB to be available.  We expect to make JAXB
available as a separate module that can be used with JDK 11 so it would be best
if Mojarra would continue to use JAXB when it is available.

Is the use of JAXB defined by the JSF spec?  If so, then you can't remove such
support without updating the spec.

**Comment by ggam** [comment]
@bshannon there were only two classes referencing JAX-B, and it was just to base64 encode and decode: https://github.com/eclipse-ee4j/mojarra/pull/4471/files

**Comment by bshannon** [comment]
Why in the world would Mojarra use JAXB classes for base64 encoding and decoding?!?!?
If there's no other support for JAXB that's exposed to users of Mojarra, then changing the
implementation to use the JDK classes for base64 encoding and decoding is obviously fine.

**Comment by ggam** [comment]
I imagine it was because before Java 8 it was the only alternative to `sun.misc.Base64` ;)

**Comment by manfredriem** [comment]
It used JAXB classes for that because that was the only one available in the JDK at the time. Note the the actual usage is an implementation detail

**Comment by chris21k** [comment]
ggam commented Sep 25, 2018
> it was just to base64 encode and decode: https://github.com/eclipse-ee4j/mojarra/pull/4471/files

So what about opening this bug again and using the correct methods of the JDK for base64 encoding and decoding: java.util.Base64 .
The dependency to jakarta.xml.bind-api.jar is absolute unnecessary and annoying (since years), e.g. using Mojarra with Tomcat.

Thanks,
Chris

**Comment by chris21k** [comment]
Unfortunately, I cannot repopen the issue, as by the transition of the old bug tracker to Github I lost the ownership of this entry.

Chris

**Comment by arjantijms** [comment]
Thanks, I'll take a look. Indeed, #4471 should have fixed this.

**Comment by arjantijms** [comment]
It appeared it was fixed in master, and that fix missed the cherry pick sessions to 2.3. It should work now. Feel free to comment here again if there's still something missing.

Thx!
