### ISSUE TITLE
JSF 2.3 Spec Section 5.9.1 and the javadocs contradict each other

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/mojarra#4389]
1) The JSF 2.3 specification in Section 5.9.1 states the following:
Support for Injection into JSF Managed Objects
It must be possible to use @Inject when specifying the following kinds of JSF managed objects.
? Validators declared with @javax.faces.validator.FacesValidator(managed=”true”)
? Converters declared with @javax.faces.convert.FacesConverter(managed=”true”)
? FacesBehaviors declared with @javax.faces.component.behavior.FacesBehavior(managed=
”true”)

2) FacesConverter is defined in the following: [FacesConverter](https://javaee.github.io/javaee-spec/javadocs/javax/faces/convert/FacesConverter.html) this lists the following target: @Target(value={TYPE,FIELD,METHOD,PARAMETER})

3) FacesValidator is defined in the following: [FacesValidator](https://javaee.github.io/javaee-spec/javadocs/javax/faces/validator/FacesValidator.html) this lists the following target: @Target(value=TYPE)

4) FacesBehavior is defined in the following: [FacesBehavior](https://javaee.github.io/javaee-spec/javadocs/javax/faces/component/behavior/FacesBehavior.html) this lists the following target: @Target(value=TYPE)

The FacesValidator and FacesBehavior should have updated targets to match FacesConverter and therefore be consistent with Section 5.9.1 of the JSF specification.

**Comment by arjantijms** [comment]
@pnicolucci 

You're right that was an oversight in 2.3 and I'll correct it in the master. Thanks for the report!

A small remark though is that technically there's no spec for the version of JSF that's at EE4J, so purely technically speaking this cannot be an issue for EE4J (from the point of view of EE4J Section 5.9.1 doesn't exists).

**Comment by kwsutter** [comment]
@arjantijms I asked Paul to create this issue here because we don't have a better spot at the moment.  I didn't want this to get lost in the Java EE -> EE4J shuffle.  We are in the process of creating a separate JSF project (separate from Mojarra).  That would be a better location for this issue when that project becomes real.  I just didn't want to lose track of the work item.  We can't do an MR for JSF 2.3 since the processes are in limbo.  But, eventually, this change needs to get into JSF 2.3.next, which will feed into Jakarta EE 9 (hopefully).  Make sense?

**Comment by arjantijms** [comment]
@kwsutter Yes, makes sense. And I agree. Just wanted to mention the technicality of that we don't have the JSF spec document anymore. Hopefully the JSF spec document will be transferred soon anyway, but at the moment not holding my breath.
