### ISSUE TITLE
What is mojarra stable version?

### ISSUE THREAD

**Issue by persapiens** [eclipse-ee4j/mojarra#4390]
Hi,

When I look after mojarra stable version [here](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.glassfish%22%20AND%20a%3A%22javax.faces%22), I see many mojarra versions: 2.3.3.102, 2.3.5, 2.4.0. Is this place correct? Which one is considered the latest stable release?

I look forward your answer.

**Comment by arjantijms** [comment]
Hi,

It’s confusing indeed due to some issues with the transfer and some commits
having been done to a branch while the transfer was in progress.

2.3.3.102 is the latest master branch release. At the time of transfer the
master was at 2.3.3. The .102 is to indicate it’s a “special” version of
2.3.3.

2.3.5 is the old 2.3.3 rolling branch, but with additional bug fixes. This
version should have never existed, but it does. It’s both a step back (it
misses all the refactoring and project improvements that went into master),
but it does have the bug fixes that should have gone into master but didn’t.

2.4.0 is a botched release. It has a faulty pom.xml and shouldn’t be used.

So it’s kinda a big mess. The lessons learned are probably the importance
of properly freezing branches and properly communicating what’s happening
to all committers.

We’ll need to fix this in one of the first Eclipse releases.

Kind regards,
Arjan

**Comment by larsgrefer** [comment]
@arjantijms `2.3.6`, `2.3.7` have been released to maven central in the meantime: https://mvnrepository.com/artifact/org.glassfish/javax.faces

Could you explain how these releases play into the "big mess" described above?
Are these releases based on `2.3.3.102` or on `2.3.5`? Or do they combine both?

**Comment by arjantijms** [comment]
@larsgrefer I tried to explain the big mess over here:

https://www.eclipse.org/lists/mojarra-dev/msg00038.html

tldr; 2.3.6 and 2.3.7 are small additions to 2.3.5.

**Comment by copernico** [comment]
Note: using the same tool that was used to report the issue at: https://github.com/javaserverfaces/mojarra/issues/4364#issuecomment-416069576
we (SAP Security Research team) found that version 2.4.0 is vulnerable to CVE-2018-14371.

The tool we used (and that we develop and operate at SAP) is available here, under the Apache 2.0 license: https://github.com/sap/vulnerability-assessment-tool

Anyone following the policy of taking the "latest available release" from Maven Central, assuming that it's the safest, will be fetching a vulnerable artifact.

How about releasing 2.4.1 immediately as an exact copy of the latest non-vulnerable version (2.3.7, as far as I understand)?

**Comment by mraible** [comment]
Related: look at the [milestones](https://github.com/eclipse-ee4j/mojarra/milestones), it says that 3.0 is 5 months past due, but it only has 5 open issues. If I were to start a new app, would you recommend using 3.0? Is there a guestimated timeline for its release?
