### ISSUE TITLE
Duplicate SessionMap annotation

### ISSUE THREAD

**Issue by tandraschko** [eclipse-ee4j/mojarra#4541]
https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/javax/faces/annotation/SessionMap.java

and

https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/javax/faces/context/SessionMap.java

**Comment by tandraschko** [comment]
same for RequestCookieMap

**Comment by tandraschko** [comment]
@arjantijms i can provide a PR here, please ping me if this will be accepted for 3.x

**Comment by arjantijms** [comment]
@tandraschko Thank. I'll start a discussion soon on the list about how to proceed with the current master.

There have been quite an amount of changes to 2.3 due to all Jakarta requirements, and there will be more needed for the javax -> jakarta package transition. Maybe it's better to rebase 3.0 again on the 2.3 branch at some point, and then redo some of the 3.0 changes (like removing the managed bean facility). I'm not 100% sure yet.

**Comment by tandraschko** [comment]
ahh i see
please let me know if you decided

The current MyFaces master equals JSF 2.3 but removed ManagedBeans and Faces EL

**Comment by arjantijms** [comment]
> The current MyFaces master equals JSF 2.3 but removed ManagedBeans and Faces EL

Yes, and some other things like project simplifications. The first step will now be to cherry-pick those project things to the 2.3 branch, and release 2.3.13. After that we need to think about the next step.
