### ISSUE TITLE
Mojarra 2.3.10 missing in Maven Repos

### ISSUE THREAD

**Issue by chris21k** [eclipse-ee4j/mojarra#4581]
http://central.maven.org/maven2/org/glassfish/jakarta.faces/ does only contain 2.3.9 and the new 2.3.10 is missing. Additionally, I was not able to build 2.3.10 from source since some necessary dependencies are not found in the maven repos.

Chris

**Comment by pzygielo** [comment]
I see 2.3.10 found its way to central.

**Comment by arjantijms** [comment]
2.3.10 was only released today indeed. @chris21k, why did you assume it was released 12 days ago? I'll check to update all dates that we have. Thx for the report.

**Comment by chris21k** [comment]
@arjantijms
Under https://github.com/eclipse-ee4j/mojarra/releases the source of v2.3.10 was (at least shown) as release much more than these 12 days ago. Is that misleading (but if where documented) and is there any schedule plan apart from that to see it in the maven repo when releases will be available?
Why is 2.3.11 release only two days after 2.3.10 then?

Please understand, that probably not only for me it is exactly in these days - after the community has fully taken over - necessary to be informed what is going on, as rather big projects are based on JEE, especially on Mojarra. A further point is that JDK and the Java language is not as "reliable" as it once was, and that new compatible library versions are more important than they ever were.

Many thx for your great commitment to Mojarra,
Chris

**Comment by arjantijms** [comment]
@chris21k Thx for the elaborate explanation. Releases are put there whenever someone runs one of the pre-release (staging) jobs on Eclipse Jenkins. I agree that looks very confusing and we should see if the job can be altered. Github has a flag for this, but not sure if the job is able to set it.  Otherwise we need to alter the name of the release bits.

Even though our friends from Oracle are still helping, there aren't the same amount of resources on the projects as before, so we need to recreate a lot of things that Oracle had in place for years (such as running the tests automatically). Incidentally, running those tests on Eclipse Jenkins is exactly what I'm going to work on next for JSF/Mojarra.

These are definitely not the easiest times, but thanks for your continuing support!
