### ISSUE TITLE
Create ROADMAP.md

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/mojarra#4614]

**Comment by arjantijms** [comment]
To be done after master branch sorted out and Mojarra 2.3.13 released.

**Comment by christophs78** [comment]
Do we (still?) plan to do a 4.x - release this year? Or do we have some other timetable?
What do we want do get into this release?

**Comment by arjantijms** [comment]
@christophs78 I think the idea for the 4.x release is indeed to happen this year, actually within months (October) al the APIs should be defined and the feature set should be final.

The broad lines for the release are still what's in the initial mail to the list about this topic:

https://eclipse.org/lists/faces-dev/msg00043.html

We got quite far a few months ago, but because of holidays etc the pace has slowed down a little. I'm currently occupied a little with the Jakarta Security APIs and the big impact of JDK 17 deprecating `Policy` and related classed.

**Comment by mnriem** [comment]
Closing this one out as 4.0 is essentially done
