### ISSUE TITLE
Add BeanManager lookup fallback to CDI.current

### ISSUE THREAD

**Issue by tandraschko** [eclipse-ee4j/mojarra#4642]
See: https://issues.apache.org/jira/browse/OWB-1298

Currently Mojarra only try to lookup the BeanManager via JDNI (Util#getCdiBeanManager).
But this requires some configration of jetty/tomcat and web.xml, which is annoying for the users.

It would be great if you could try CDI.current instead of returning null. We do the same in MyFaces

**Comment by arjantijms** [comment]
CDI.current first might be problematic because of e.g. this report:

https://issues.jboss.org/browse/WELD-2510

See also this one:

https://github.com/eclipse-ee4j/soteria/pull/243

Given that, it might be an option to try CDI.current *last*. 

The idea would be that in runtimes that support EARs, JNDI is basically always supported as well. Jetty/Tomcat don't support EARs, so they would fall back to the problematic CDI.current, which however won't be problematic to them.

What do you think?

**Comment by tandraschko** [comment]
yep, why not
it doesn't matter if first or last, the important thing is to avoid NPEs for users :)

**Comment by arjantijms** [comment]
Yes, avoiding that is important, although avoiding unpredictable behaviour is also important ;)

I'm not entirely sure what to think of CDI.current and where its current problems must be fixed. The Weld team said it's an integration issue, so that would put the blame on GlassFish etc, but I'm not 100% sure.

**Comment by rmannibucau** [comment]
Using CDI.current() or a JNDI lookup should end with the same behavior if we want applications to be portables (it is the only defined way to get a contextual instance) - whatever the integration handles it or the CDI core impl is an implementation details so it can be the full server integration or weld, it is not important.
That said, using CDI.current() as a last fallback does not hurt in all cases (it is better than failling or returning null).
So maybe just reverse the "first" of the issue ;)

**Comment by christophs78** [comment]
You may assign this issue to me. PR propably comming within a week.

**Comment by christophs78** [comment]
This one may be closed because already implemented by @BalusC with https://github.com/eclipse-ee4j/mojarra/commit/98189bea9d485c8bf459718eae1e127b063c4fad#diff-6e59848a7dc34c64f4c25e5afc623099e1262d1161223a33eec9570569242aeb.
Is it an option to release 2.3.17?

**Comment by BalusC** [comment]
Indeed already implemented in 2.3.17.
