### ISSUE TITLE
UIData invokeOnComponent should call invokeOnComponent on its facets too

### ISSUE THREAD

**Issue by gndrm** [eclipse-ee4j/mojarra#4667]
When UIData#invokeOnComponent iterates over its facets, then only 
`callback.invokeContextCallback` is called. That Way facets of uidata are not allowed to have children. This is a limitation for use of dynamic components. Instead of 

```
        if (this.getFacetCount() > 0) {
            for (UIComponent c : this.getFacets().values()) {
                if (clientId.equals(c.getClientId(context))) {
                    callback.invokeContextCallback(context, c);
                    return true;
                }
            }
        }
```
the loop should be changed to

```
        if (this.getFacetCount() > 0) {
            for (UIComponent c : this.getFacets().values()) {
                if(c.invokeOnComponent(context, clientId, callback)) {
                	return true;
                }
            }
        }
```

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
