### ISSUE TITLE
Problem with WebSocket in mixed secure/unsecure environment

### ISSUE THREAD

**Issue by michael-knapp-j4care** [eclipse-ee4j/mojarra#4676]
I have a problem at a customer's site:

I get the same error message like in the following issue, but the fix provided there does not provide a solution to my problem: https://github.com/eclipse-ee4j/mojarra/issues/4527

Browser connects via TLS to some secure proxy, the proxy itself connects via unsecure http to the application server. The application server is not aware of that secure communication in the browser and generates the unsecure ws:// URL, which is rendered to the HTML output. Since the page was invoked with https:// the ws:// causes the described problems

My proposed solution: it should be decided on client side (in jsf.js) when to use ws:// or wss://

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
