### ISSUE TITLE
2.3.15 release date

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [eclipse-ee4j/mojarra#4715]
some important changes have been made to branch 2.3.  could someone release 2.3.15, please?

**Comment by arjantijms** [comment]
It's about indeed.

**Comment by ttsiebzehntt** [comment]
@arjantijms It's been a while... Will there even be a 2.3.15 release?

**Comment by melloware** [comment]
Bump

**Comment by christophs78** [comment]
Would be a good thing to release 2.3.15 within the next days/weeks.
A couple of people (including the organisation i work for on my day job) wait for this as prerequisite to be able to upgrade to PrimeFaces 10.

**Comment by christophs78** [comment]
Hi @arjantijms!
You did 2.3.15-M1. Thanks!
Is there a chance to get this published to MavenCentral like 4.0.0-M1?
Kind regards,
Christoph

**Comment by arjantijms** [comment]
@christophs78 2.3.15-M1 failed the TCK, but @BalusC discovered at least one major cause of the failure that should be easy to correct.

@BalusC do you have any status on this?

**Comment by christophs78** [comment]
Do we have the same issue today? What´s the difference between our usual CI which run´s after each commit and setting a  version-tag?

**Comment by arjantijms** [comment]
> What´s the difference between our usual CI 

Do you mean Travis? Travis now just builds the branch (mvn clean install, effectively), while the TCK runs for close to 3 hours and executes over 5000 tests.

You can see it here, I just kicked off a new run: https://ci.eclipse.org/mojarra/job/2_mojarra-run-tck-against-staged-build_2_3/

It should finish in about 1 hour against the staged 2.3.15. If it passed (which it really should, since nothing changed), I can *finally* push the release button ;)

**Comment by christophs78** [comment]
Ok. New things to learn. :-)
Eclipse uses it´s own Jenkins-instance for running integration-tests. And this get´s triggerd by some eclipse "magic"? Or manually? 
And we (you?) can run this on demand also against every branch we wan´t to check?

Just was confused before due to
![image](https://user-images.githubusercontent.com/10461942/116883438-e4f59800-ac25-11eb-927c-642d796a8a63.png)

**Comment by arjantijms** [comment]
Yes and no ;)

Mojarra is one of the few projects EE4J were the integration tests don't run automatically. But for most other projects this would be yes and yes indeed. It can be triggered by a commit hook I think, or by the Eclipse Jenkins CI periodically scanning the repo for new commits.

Then there's the TCK tests, which are not executed automatically for any EE4J repo as far as I know. This is an extended set of tests that are only run on demand. Every committer of a project can run them by logging into the CI that's associated with a project. Not every project may have their TCK tests set up, but I did so for all projects I'm involved with.

There's also an overal CI that runs all the TCKs from the TCK project's point of view, against a given GlassFish version.

**Comment by melloware** [comment]
This ticket can be closed.
