### ISSUE TITLE
JSF deployment failure due to UnsupportedOperationException when javax.faces.FACELETS_VIEW_MAPPINGS is defined

### ISSUE THREAD

**Issue by RanabirChakraborty** [eclipse-ee4j/mojarra#4735]
1. Configure the following javax.faces.FACELETS_VIEW_MAPPINGS setting in web.xml of your JSF application (For example, add the following web.xml to [tasks-jsf](https://github.com/jboss-developer/jboss-eap-quickstarts/tree/7.3.x/tasks-jsf) in JBoss EAP QuickStarts):
```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"                  
         version="4.0">
    <context-param>
        <param-name>javax.faces.FACELETS_VIEW_MAPPINGS</param-name>
        <param-value>*.jsp</param-value>
    </context-param>
</web-app>
```
2.  Start Wildfly 20.0.1.Final and Deploy the application

3. You will see the deployment failure due to "UnsupportedOperationException: UT010042: This method cannot be called from a servlet context listener that has been added programmatically"
```
SEVERE [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 84) Critical error during deployment: : java.lang.UnsupportedOperationException: UT010042: This method cannot be called from a servlet context listener that has been added programatically
	at io.undertow.servlet.spec.ServletContextImpl.ensureNotProgramaticListener(ServletContextImpl.java:976)
	at io.undertow.servlet.spec.ServletContextImpl.getServletRegistrations(ServletContextImpl.java:584)
	at com.sun.faces.util.Util.getExistingFacesServletRegistration(Util.java:160)
	at com.sun.faces.util.Util.getFacesServletMappings(Util.java:150)
	at com.sun.faces.util.Util.isResourceExactMappedToFacesServlet(Util.java:1158)
	at com.sun.faces.util.Util.isViewIdExactMappedToFacesServlet(Util.java:1139)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.handlesViewId(FaceletViewHandlingStrategy.java:946)
	at com.sun.faces.application.view.ViewHandlingStrategyManager.getStrategy(ViewHandlingStrategyManager.java:76)
	at com.sun.faces.application.view.ViewDeclarationLanguageFactoryImpl.getViewDeclarationLanguage(ViewDeclarationLanguageFactoryImpl.java:47)
	at com.sun.faces.application.view.MultiViewHandler.getViewDeclarationLanguage(MultiViewHandler.java:446)
	at javax.faces.application.ViewHandlerWrapper.getViewDeclarationLanguage(ViewHandlerWrapper.java:346)
	at javax.faces.application.ViewHandlerWrapper.getViewDeclarationLanguage(ViewHandlerWrapper.java:346)
	at 
```
Widlfy issue is [here](https://issues.redhat.com/browse/WFLY-13792)

**Comment by rmartinc** [comment]
Just some context about this issue. Wildfly/undertow added a feature recently to better follow the servlet 4.0 spec and now it forbids the usage of the `ServletContext.getServletRegistrations` method when the registration is programmatic. This is also valid for servlet context listeners that are registered using a TLD, like the `ConfigureListener` in the mojarra implementation. Check the [servlet 4.0 spec](https://javaee.github.io/servlet-spec/downloads/servlet-4.0/servlet-4_0_FINAL.pdf) in chapter 8.3 - JSP container pluggability:

bq. Any ServletContextListeners that were discovered in a TLD and registered programmatically are limited in the functionality they provide. Any attempt to call a ServletContext API methods on them that was added since Servlet 3.0 will result in an UnsupportedOperationException.

Don't know if this happens in other javaee servers but in wildfly adding the parameter FACELETS_VIEW_MAPPINGS (not containing the `*.xhtml` value) triggers this issue. The `ConfigureListener` finally calls `getServletRegistrations` in the `ServletContext`. See the stack-trace in the issue. In the associated PR @RanabirChakraborty is saving the `FacesServlet` mappings in a servlet attribute during initialization (like the impl is doing now for the annotated classes for example) to avoid the call from the listener. Another solution would be modifying in the [ApplicationAssociate](https://github.com/eclipse-ee4j/mojarra/blob/3.0/impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java#L320) to not use `xhtml` directly but using something got from the parameter.

@arjantijms WDYT? The workaround is more or less easy but this can trigger a lot of noise in wildfly users...

**Comment by fjuma** [comment]
@arjantijms Would you be able to take a look at the PR that @RanabirChakraborty created for this issue? Thanks!

**Comment by BalusC** [comment]
All merged.

Made sure it's in 2.3/3.0/4.0.

**Comment by BalusC** [comment]
Thank you for your contribution!

**Comment by BalusC** [comment]
All existing tests have passed in 2.3 :+1:
