### ISSUE TITLE
More schema updates to jakartaee required

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/mojarra#4737]
This issue should be in continuation with https://github.com/eclipse-ee4j/mojarra/issues/4725

There are more references of javaee xsds in 
 ./impl/src/main/resources/com/sun/faces/facelets1_0-2_0toSchema.xsl
./impl/src/main/resources/com/sun/faces/metadata/taglib/jstl-fn.taglib.xml
./impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml
./impl/src/main/resources/META-INF/mojarra_ext.taglib.xml

After the jsf TCK was updated using PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/481  we encounter 8 test failures as in https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/60. 

cc @scottmarlow @gurunrao @arjantijms

**Comment by smillidge** [comment]
I'll need a new RC for integrating into GlassFish

**Comment by arjantijms** [comment]
@smillidge Okay, I'll look at a new RC, and will also stage the Faces API with the latest dependencies update.

There's currently an error in the Mojarra 3.0 (complaint about unknown version), so I have to take look what's causing that.

**Comment by alwin-joseph** [comment]
Is the new RC scheduled to be released and integrated to glassfish soon.

**Comment by arjantijms** [comment]
> @arjantijms Is the new RC scheduled to be released yet ? So @smillidge can integrate it to glassfish ?

There were multiple issues with RC3. One issue was related to an internal config file having the wrong namespace. I looked at this several time but just missed it, my apologies for that. I finally found it after debugging into the very depth of the thing.

Another issue had to do with CDI activation and the 2.3 and pre-2.3 version in the faces-config file that was used for this before. With all config files updated to 3.0, some tests were breaking because of this. I staged -RC4 and I'm now running the TCK against it. So far it looks good, but it's only half-way at the time of writing.

**Comment by mnriem** [comment]
@alwin-joseph Can you supply a fix?

**Comment by alwin-joseph** [comment]
> @alwin-joseph Can you supply a fix?

Fix in mojarra or tck ? 

Actually this issue was created for JakartaEE 9 for which fix was made using PR4738 but now the schemas may need to be updated with JakartaEE 10  namespaces. There are xsds missing in https://jakarta.ee/xml/ns/jakartaee/#10 , eg: web-facelettaglibrary*.xsd. Were you asking to do similar schema update for JakartaEE 10 ?

**Comment by mnriem** [comment]
@arjantijms Has this been resolved? @alwin-joseph If not can you supply a PR that fixes the issues you have found?

**Comment by BalusC** [comment]
Closing off as stale.
