### ISSUE TITLE
Problem with state saving of dynamic components with/or without stateless view

### ISSUE THREAD

**Issue by przemcio** [eclipse-ee4j/mojarra#4824]
I have created an issue in original mojarra project.

https://github.com/javaserverfaces/mojarra/issues/4438

There is an inconsequence in recreation of the component tree. 

Is there any proper approach to use transient/not transient components with dynamic sub tree components?

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer using only core Mojarra and if you can create a PR fixing the issue
