### ISSUE TITLE
Deprecate IE6-7-8-9 and all older browsers support

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/mojarra#5044]
I propose we state in the documentation comments of faces-uncompressed.js that Mojarra will only target support for Edge 97+, Firefox 96+, Chrome 98+, Safari 15.2+, Opera 83+ and all others are deprecated.

See issue #5040 for background

**Comment by pizzi80** [comment]
We could also mention that the file should be 

ECMAScript 2015 (ES6)

[https://www.w3schools.com/js/js_versions.asp](https://www.w3schools.com/js/js_versions.asp)

[https://www.w3schools.com/js/js_es6.asp](https://www.w3schools.com/js/js_es6.asp)

**Comment by mnriem** [comment]
@arjantijms What are your thoughts?

**Comment by codylerum** [comment]
I think it is time. Those who still need to support IE will obviously lag behind, but they likely would not be adopting 4.0+ for a few more years anyway.

**Comment by BalusC** [comment]
> Edge 97+, Firefox 96+, Chrome 98+, Safari 15.2+, Opera 83+ 

It's better to target a specific browser feature rather than a specific browser version. E.g. "ES6 is required" or even "ES2020 is required".

As first step, we really really need to revive all missing integration tests from 2.3 branch into 4.0 (master) branch as a rather big part of them (in)directly test the jsf.js/faces.js, including all known and unknown corner cases. 

Once done that, then I'd like to migrate the faces.js to use the TypeScript language which allows us to (re)compile them for a specific ES version. I.e. we can have a single script source implementing es.next and be able to have multiple build targets if necessary, including ES5 or even ES3 if absolutely necessary. I've already kicked off a working approach in OmniFaces: https://github.com/omnifaces/omnifaces/pull/675

**Comment by BalusC** [comment]
Just noticed there's already a TS impl https://github.com/werpu/jsfs_js_ts, mentioned here https://github.com/jakartaee/faces/issues/1598.

**Comment by pizzi80** [comment]
is it still relevant to use TypeScript for jsf ?

jsf 4+ is still not available and probably will be adopted by devs during 2023 
and for that time all the web browsers will support 
javascript  classes / modules / private fields / public fields ...

just saying ...

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#examples](url)

**Comment by arjantijms** [comment]
Faces 4 is currently in ballot. The ballot will end in a few days, and then I'll push the staged API jars out to central.

We can then use master for this and other issues.
