### ISSUE TITLE
Component wrapping does not work properly in 2.3.17

### ISSUE THREAD

**Issue by fcjm** [eclipse-ee4j/mojarra#5065]
**Describe the bug**

We recently upgraded our Wildfly to version 26.0.1 which now provides JSF version 2.3.17. We have a case in which we use simple composite components which can wrap more complex components (more specificly the PrimeFaces DataTable). If the wrapping component only consists of simple html-Elements, the wrapped component will not work properly. First I thought this might be a problem with PrimeFaces, so I created a primefaces-test project reproducing the issue (see below). But when starting the project with Mojarra 2.3.17 the problem is reproducable, while with mojarra 2.3.16 it is not. This was causing me to believe that there might be a problem with the current Mojarra 2.3.17 release.

**To Reproduce**
[reproducer.zip](https://github.com/eclipse-ee4j/mojarra/files/8204615/reproducer.zip)

1. Start the reproducer via 'mvn clean jetty:run -Pmojarra2317'
2. Go to 'http://localhost:8080/primefaces-test/working.xhtml' (welcome-page)
3. Sort/Filter the DataTable -> works
4. Go to 'http://localhost:8080/primefaces-test/notworking.xhtml'
5. Sort/Filter the DataTable -> does not work

I have also added a profile -Pmojarra2316 which you can use to counter-check that it actually did work with Mojarra 2.3.16.

**Expected behavior**

Same behaviour as Mojarra 2.3.16 (working)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser Chrome
 - Version 99.0.4844.51

**Additional context**

We found a workaround for now which consists of using facelet-tags instead of composite components in this scenario. When doing that, the clientId gets shortened, since the wrapping components Id does no longer show up in it. So I suspect the issue might lie in the detection of components on server-side. Unfortunately though I was not able to find any evidence for this. It would be great if someone with more insight could take a look at it.

**Comment by mnriem** [comment]
Please remove PrimeFaces from the mix altogether to see if it is Mojarra causing the issue.

**Comment by OBreidenbach** [comment]
I created a reproducer without primefaces, so it is still the testcase provided from primefaces but I removed all decencies to primefaces.
[reproducr_without_primefaces.zip](https://github.com/eclipse-ee4j/mojarra/files/8242508/reproducr_without_primefaces.zip)

This reproducer uses just a <h:selectOneListbox>, but it could be any component.
As I said in my former comment, the component object instance is not found in the cache and so a new one is created. As some primefaces components keep state in the object instance during a request, the state got lost.

My example contains 2 views.

- /test/sendEntireForm.xhtml
- /test/sendOnChange.xhtml

In the logging of both you will see, that for the component which is wrapped in the 'htmlWrapper' during RENDER_RESPONSE a new object instance is created. This does not happen, if no composite component is used or there is a other component in the composite component. 

This only happens with Mojarra 2.3.17, it does not happen with Mojarra 2.3.16. Then the object instance stays the same during the request.

**Comment by mnriem** [comment]
Probably a regression because of #4934

**Comment by BalusC** [comment]
Excellent analysis/reproducer, very helpful. And yes Manfred this indeed looks like to be a regression of this original work: https://github.com/eclipse-ee4j/mojarra/pull/4808

**Comment by BalusC** [comment]
Okay, nailed down. This does at first glance not seem to be a regression but just an existing bug being uncovered which was previously seemingly worked around with the original inefficient implementation of `ComponentSupport#findChildByTagId()`.

`ComponentTagHandlerDelegateImpl#apply()` looks like this: https://github.com/eclipse-ee4j/mojarra/blob/2.3.17-RELEASE/impl/src/main/java/com/sun/faces/facelets/tag/jsf/ComponentTagHandlerDelegateImpl.java#L120
```
        // grab our component
        UIComponent c = findChild(ctx, parent, id);
        if (null == c &&
            context.isPostback() &&
            UIComponent.isCompositeComponent(parent) &&
            parent.getAttributes().get(id) != null) {
            c = findReparentedComponent(ctx, parent, id);
        }
```
Technically speaking, the `<h:selectOneListbox>` in question is reparented (i.e. handled via `InsertChildrenHandler`). So, during render response of a postback, you'd expect `findChild()` which delegates to `ComponentSupport#findChildByTagId()` to return `null` and then the logic will eventually find it via `findReparentedComponent()`. But this did not happen in 2.3.16 and before. It was found right away via `findChild()`.

Since the performance optimizations of `ComponentSupport#findChildByTagId()`, the `findChild()` returns `null`, which is completely expected, because the `<h:selectOneListbox>` is reparented, but the `findReparentedComponent()` unexpectedly returned `null`. And then the logic will create a new component, which is incorrect and explains the observable problems.

As to reparenting, during view build time of postback, the composite component basically creates during `CompositeComponentTagHandler#applyCompositeComponent()` an `UIPanel` representing the `<cc:implementation>`: https://github.com/eclipse-ee4j/mojarra/blob/2.3.17-RELEASE/impl/src/main/java/com/sun/faces/facelets/tag/jsf/CompositeComponentTagHandler.java#L321 
```
        if (ComponentHandler.isNew(c)) {
            facetComponent = (UIPanel)
            facesContext.getApplication().createComponent("javax.faces.Panel");
            facetComponent.setRendererType("javax.faces.Group");
            c.getFacets().put(UIComponent.COMPOSITE_FACET_NAME, facetComponent);
        }                                                                                 
```
All direct children are then reparented against it and this is tracked in `InsertChildrenHandler#processEvent()`: https://github.com/eclipse-ee4j/mojarra/blob/2.3.17-RELEASE/impl/src/main/java/com/sun/faces/facelets/tag/composite/InsertChildrenHandler.java#L154
```
            //store the new parent's info per child in the old parent's attr map
            //<child id, new parent>
            for (UIComponent c : compositeChildren) {
                String key =  (String)c.getAttributes().get(ComponentSupport.MARK_CREATED);
                String value = component.getId();
                if (key != null && value != null) {
                    compositeParent.getAttributes().put(key, value);
                }
            }
```
Here `component` is exactly the same as `facetComponent`. However, its `getId()` returned `null`. This has as consequence that `ComponentTagHandlerDelegateImpl#apply()` won't invoke `findReparentedComponent()` because `parent.getAttributes().get(id)` returned `null`.
```
        // grab our component
        UIComponent c = findChild(ctx, parent, id);
        if (null == c &&
            context.isPostback() &&
            UIComponent.isCompositeComponent(parent) &&
            parent.getAttributes().get(id) != null) {
            c = findReparentedComponent(ctx, parent, id);
        }
```
The fix was to trigger ID generation in `CompositeComponentTagHandler#applyCompositeComponent()` as can be seen in commit https://github.com/eclipse-ee4j/mojarra/commit/f28d7d26879f2ac61b3221cfdbf1fb8880f9ba08

Will add IT later after I've verified that all existing tests pass.

**Comment by OBreidenbach** [comment]
@BalusC, thank you for the fixing this so fast.
