### ISSUE TITLE
"javax.faces.WEBAPP_RESOURCES_DIRECTORY" behavior is not correct.

### ISSUE THREAD

**Issue by fukumotyo** [eclipse-ee4j/mojarra#5118]
**Describe the bug**

The API document below states that it must not start with a "/", but if it does not start with a "/", it will not work.

[ResourceHandler#WEBAPP_RESOURCES_DIRECTORY_PARAM_NAME](https://jakarta.ee/specifications/faces/2.3/apidocs/javax/faces/application/resourcehandler#WEBAPP_RESOURCES_DIRECTORY_PARAM_NAME)

**To Reproduce**

1. Set the following in web.xml
```xml
  <context-param>
    <param-name>javax.faces.WEBAPP_RESOURCES_DIRECTORY</param-name>
    <param-value>WEB-INF/resources</param-value>
  </context-param>
```
2. Describe the resource to be loaded in the JSF file.
```xml
  <h:outputScript library="myjs" name="myapp.js" />
  <h:outputStylesheet library="mycss" name="mystyle.css" />
```
3. Create the following resource files
```
  WEB-INF/resources/myjs/myapp.js
  WEB-INF/resources/mycss/mystyle.css
```

**Expected behavior**

Resource files described in the JSF file must be loaded.

**Comment by BalusC** [comment]
Wow, that's an awkward oversight there.

The original spec issue is this: https://github.com/jakartaee/faces/issues/996
There's even a comment pointing out this deviation: https://github.com/jakartaee/faces/issues/996#issuecomment-518574116
I guess the deviation was caused by mix-up of two initial proposals as commented here: https://github.com/jakartaee/faces/issues/996#issuecomment-518574106

For now the Mojarra impl should silently prepend the / when absent and we'll need a new spec ticket to adjust or drop this requirement.

**Comment by fukumotyo** [comment]
I should have added at the beginning that WEBAPP_CONTRACTS_DIRECTORY has the same problem.

**Comment by fukumotyo** [comment]
I should have added at the beginning that WEBAPP_CONTRACTS_DIRECTORY has the same problem.

The operation was closed by mistake and will be reopened.

**Comment by fukumotyo** [comment]
I should have added at the beginning that WEBAPP_CONTRACTS_DIRECTORY has the same problem.

The operation was closed by mistake and will be reopened.

**Comment by BalusC** [comment]
Confirmed. I'll adjust that one as well.
