### ISSUE TITLE
h:commandButton change the rendering to html button instead of input

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5382]
Why not render the html `<button type="submit" />` tag instead of the `<input type="submit" />`

Also the name "_commandButton_" suggests that a button will be rendered
like the "_commandLink_" renders an html _"link"_ (anchor)

eventually the input type submit could be rendered 
on a new component ... something like
`<h:command />` or `<h:submit />`

**Comment by BalusC** [comment]
[This is already set in stone since JSF 1.0 spec](https://jakarta.ee/specifications/faces/4.0/vdldoc/h/commandbutton). Rather open an issue in jakartaee/faces. I looked around there and found that this was previously already requested: https://github.com/jakartaee/faces/issues/1018

I'm not sure why input is chosen instead of button, I wasn't involved in the JSF 1.0 works.

**Comment by pizzi80** [comment]
Thanks for the reply, 

I commented on the issue in the Faces API, even if it seems like an abandoned ticket...

Someone commented that it would be implemented in JSF 2.3 
but I think that's been completely forgotten

I don't know what the procedure is to get it reconsidered ...
